name: Run Bash Scripts Tests

on:
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
     - name: Checkout repository
       uses: actions/checkout@v3

     - name: set execute permission to backup script
       run: chmod +x ./bin/backup.sh

     - name: Set execute permission to test script
       run: chmod +x ./tests/test_backup.sh


     - name: Run backup test script       
       run: ./tests/test_backup.sh 

  